name: github-actions
on: pull_request
jobs:
  run-main-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '8'
      - run: java HelloWorld.java
